### PR TITLE
fix: allow user to update phone number

### LINKED ISSUE #390: PUT /user should allow update of phone field
# Bug report
* Currently, the `PUT /user` endpoint doesn't allow a user to update the phone field.

# Solution
* The `PUT /user` endpoint should update the phone field and also trigger sending out an OTP to verify the phone number used. 
* If `GOTRUE_SMS_AUTOCONFIRM` is enabled, then the `PUT /user` endpoint should update the phone field without sending out an OTP.

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Fixes #390 
* If `GOTRUE_SMS_AUTOCONFIRM` is enabled, an otp will not be sent to the new phone number, else, an otp will be sent to the new phone number and the user has to verify it first.
* Added a new verification type called `phone_change` which when set, will verify if the token sent is valid when compared to the `phone_change_token` and `phone_change_sent_at` fields

## To-Do
* Update gotrue-js to include the `phone_change` verification type (https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L202)

### CODE REVIEW

File: api/phone.go [hunk 1]
```diff
@@ -29,39 +34,51 @@ func (a *API) formatPhoneNumber(phone string) string {
 	return strings.ReplaceAll(strings.Trim(phone, "+"), " ", "")
 }
 
-func (a *API) sendPhoneConfirmation(ctx context.Context, tx *storage.Connection, user *models.User, phone string) error {
+// sendPhoneConfirmation sends an otp to the user's phone number
+func (a *API) sendPhoneConfirmation(ctx context.Context, tx *storage.Connection, user *models.User, phone, otpType string, smsProvider sms_provider.SmsProvider) error {
```
Comment (kangmingtay) [inline api/phone.go:38]: Changed the function signature here to take in an `otpType` and a `smsProvider`. The `smsProvider` was added to the function params to make it easier to test this function with a mock sms provider that implements a stub `SendSms` method. See [TestSendPhoneConfirmation](https://github.com/supabase/gotrue/pull/421/files#diff-10c35f776118e94548a7f2835c538ba3996e74fdf24df35e5591922bad18d8b9R66)

File: api/phone.go [hunk 2]
```diff
@@ -29,39 +34,51 @@ func (a *API) formatPhoneNumber(phone string) string {
...
+		tokenDbField, sentAtDbField = "confirmation_token", "confirmation_sent_at"
+	} else if otpType == phoneChangeOtp {
+		token = &user.PhoneChangeToken
+		sentAt = user.PhoneChangeSentAt
+		tokenDbField, sentAtDbField = "phone_change_token", "phone_change_sent_at"
+	} else {
+		return internalServerError("invalid otp type")
+	}
+
+	if sentAt != nil && !sentAt.Add(config.Sms.MaxFrequency).Before(time.Now()) {
```
Comment (J0) [inline api/phone.go:57]: /nit 

personal preference but something of the style `(time.Now()).After(sentAt.Add(config.Sms.MaxFrequency))`  might be slightly more readable.  Not sure that this compiles though.

Not expecting any change, just leaving it here as another possibility to consider

File: go.sum [hunk 3]
```diff
@@ -539,6 +539,7 @@ github.com/spf13/viper v1.4.0/go.mod h1:PTJ7Z/lr49W6bUbkmS1V3by4uWynFiR9p7+dSq/y
 github.com/spf13/viper v1.7.0/go.mod h1:8WkrPz2fc9jxqZNCJI/76HCieCp4Q8HaLFoCha5qpdg=
 github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
 github.com/stretchr/objx v0.1.1/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
+github.com/stretchr/objx v0.2.0 h1:Hbg2NidpLE8veEBkEZTL3CvlkUIVzuU9jDplZO54c48=
```
Comment (J0) [inline go.sum:542]: Guessing this is from

`"github.com/stretchr/testify/mock"`
