### PR TITLE
Change recover password to not return user not found error

### LINKED ISSUE #338: Don't throw 'User not found' in resetPasswordForEmail
# Bug report

## Describe the bug
Less of a bug and more of a security concern. Right now `supabase.auth.api.resetPasswordForEmail` throws a "User not found" error when auth account doesn't exists in db. This can be abused to test list of emails agains auth db in order to figure out if particular email is a user of the app and launch phishing attacks against them.

## To Reproduce
Just call `supabase.auth.api.resetPasswordForEmail` with email that was never used to authenticate with your app.

## Expected behavior

Should return success even with invalid email and not send reset password email in user does not exist.

## System information

- OS: all
- Browser: all
- Version of supabase-js: 1.29.1
- Version of Node.js: all

### PR DESCRIPTION
**Pull request by J0**
## What kind of change does this PR introduce?

Fix #338 

## What is the current behavior?

Returns user not found error

## What is the new behavior?

Does not return user not found error

## Additional context

TODOs:
- Check for constant time return

### CODE REVIEW

File: api/recover.go [hunk 1]
```diff
@@ -32,12 +32,6 @@ func (a *API) Recover(w http.ResponseWriter, r *http.Request) error {
 
 	aud := a.requestAud(ctx, r)
 	user, err := models.FindUserByEmailAndAudience(a.db, instanceID, params.Email, aud)
-	if err != nil {
```
Comment (kangmingtay) [inline api/recover.go:35]: i think we still need to check if it's an error here and return some generic error message? otherwise it will panic [here](https://github.com/supabase/gotrue/pull/359/files#diff-fe4851c1c04b9250f3e6f83565798c83a3b1e65a7af256711ff89fab7cae627cR37) if the user is nil

File: api/recover.go [hunk 2]
```diff
@@ -48,11 +42,8 @@ func (a *API) Recover(w http.ResponseWriter, r *http.Request) error {
 		referrer := a.getReferrer(r)
 		return a.sendPasswordRecovery(tx, user, mailer, config.SMTP.MaxFrequency, referrer)
 	})
-	if err != nil {
-		if errors.Is(err, MaxFrequencyLimitError) {
-			return tooManyRequestsError("For security purposes, you can only request this once every 60 seconds")
-		}
-		return internalServerError("Error recovering user").WithInternalError(err)
```
Comment (kangmingtay) [inline api/recover.go:55]: same here, this error could possibly be due to an error from the transaction above, we need to check it and probably return a more generic error message than not at all

**Review by kangmingtay — CHANGES_REQUESTED** [review]

File: api/recover.go (hunk 1 above)
Comment (J0) [reply api/recover.go:35]: Thanks for the catch! That makes sense. I'm not too sure we can return an error message though since any error message would give away information (since GoTrue is OSS and the attacker can look up the code). Might make sense to return 200/ Will think about this and address later in the evening.

**Comment by chadyj** [comment]
Great to see this fix. Thank you.

For some context, here is the result we are showing to the user in the UX. It works for scenarios in which an account exists or does not exist:

> If an account exists, you will receive an email with instructions on how to reset your password.

This is based on the [OWASP cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#forgot-password-request). 

> - Return a consistent message for both existent and non-existent accounts.
> - Ensure that responses return in a consistent amount of time to prevent an attacker enumerating which accounts exist. This could be achieved by using asynchronous calls or by making sure that the same logic is followed, instead of using a quick exit method.

**Review by kangmingtay — APPROVED** [review]
