### PR TITLE
fix: return user for POST verify endpoints

### LINKED ISSUE #141: Return user on successful /POST verify
# Bug report
Current JSON response returned on successful POST /verify contains `user: null` 

Reason for current implementation: Netlify upstream originally returns `user:null` on the /verify endpoint

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Fixes #141 
* Decided that for DX purposes, returning the user object after verification is fine.
* Unblocks https://github.com/supabase/gotrue-js/pull/228

### CODE REVIEW

File: api/token.go [hunk 1]
```diff
@@ -348,8 +347,8 @@ func (a *API) IdTokenGrant(ctx context.Context, w http.ResponseWriter, r *http.R
 	if params.IdToken == "" || params.Nonce == "" {
 		return oauthError("invalid request", "id_token and nonce required")
 	}
-	
-	if params.Provider == "" && ( params.ClientID == "" || params.Issuer == "" ) {
+
+	if params.Provider == "" && (params.ClientID == "" || params.Issuer == "") {
```
Comment (kangmingtay) [inline api/token.go:351]: just formatting changes which gofmt did automatically

File: api/token.go [hunk 2]
```diff
@@ -81,7 +81,7 @@ func (p *IdTokenGrantParams) getVerifier(ctx context.Context) (*oidc.IDTokenVeri
 		if url == "" {
 			url = "https://login.microsoftonline.com/common"
 		}
-		provider, err = oidc.NewProvider(ctx, url + "/v2.0")
+		provider, err = oidc.NewProvider(ctx, url+"/v2.0")
```
Comment (kangmingtay) [inline api/token.go:84]: formatting changes, ignore

File: api/token.go [hunk 3]
```diff
@@ -55,7 +55,7 @@ type IdTokenGrantParams struct {
 	Nonce    string `json:"nonce"`
 	Provider string `json:"provider"`
 	ClientID string `json:"client_id"`
-	Issuer string `json:"issuer"`
+	Issuer   string `json:"issuer"`
```
Comment (kangmingtay) [inline api/token.go:58]: formatting changes, ignore

File: api/token.go [hunk 4]
```diff
@@ -558,6 +551,7 @@ func (a *API) issueRefreshToken(ctx context.Context, conn *storage.Connection, u
 		TokenType:    "bearer",
 		ExpiresIn:    config.JWT.Exp,
 		RefreshToken: refreshToken.Token,
+		User:         user,
```
Comment (kangmingtay) [inline api/token.go:554]: basically add the user object to the token struct returned so calling `issueRefreshToken` will now embed the user object in the struct as well

**Review by thorwebdev — APPROVED** [review]
LGTM
