### PR TITLE
Fix: Allow refresh token grant if no email in providers field

### LINKED ISSUE #276: Token refresh API only works when Email Auth is enabled
### Discussed in https://github.com/supabase/supabase/discussions/3874

<div type='discussions-op-text'>

<sup>Originally posted by **davidmuzi** November 12, 2021</sup>
Im currently using Sign in with Apple, and am able to successfully make user authenticated calls using the returned JWT. However, when I attempt to refresh the token, I get a 400 response.

```
curl -X "POST" "https://avql....supabase.co/auth/v1/token?grant_type=refresh_token" \
     -H 'apikey: eyJhbGci...' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{"refresh_token": "u14G..."}'
```
Response:
`{"code":400,"msg":"Email logins are disabled"}` 

If I enable Email Auth in settings, then it works, but Im only interested in using Apple login.
</div>

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Fixes #276 
* If the `providers` field returned contains "email", we still don't allow a user to use the refresh token. This is because it is impossible to tell if the user is refreshing a token for an email login or oauth provider login.

### CODE REVIEW

File: api/token.go [hunk 1]
```diff
@@ -234,6 +240,21 @@ func (a *API) RefreshTokenGrant(ctx context.Context, w http.ResponseWriter, r *h
 		return internalServerError(err.Error())
 	}
 
+	if !(config.External.Email.Enabled && config.External.Phone.Enabled) {
```
Comment (awalias) [inline api/token.go:243]: just double checking this is the logic you want?

!(a && b) == (!a || !b)

**Review by awalias — APPROVED** [review]

File: api/token.go (hunk 1 above)
Comment (kangmingtay) [reply api/token.go:243]: Yeah if both email and phone logins are enabled, we never need to check. So for the inverse cases (either email or phone is disabled or both disabled), we should always check.
