### PR TITLE
fix: send otp in email link

### LINKED ISSUE #139: Email Confirm and Password reset via code
Hi Team,
Is it possible for email confirmation, we can ask users to enter the verification code rather than clicking the link?

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Fixes #139, #264, #368 
* Sends the OTP (which can either be a confirmation / invite / recovery / email change token) in the email together with the url link
* Developers can choose to omit `{{ .ConfirmationURL }}` from their email templates to prevent cases where email clients preview the URL thus resulting in the token being consumed. (addresses #368)

## API Additions / Changes
1. `POST /verify` now accepts an `email` field which would be used together with the token to verify the user. 
```json
{
  "type": "signup",
  "email": "foo@example.com",
  "token": "random token",
  "redirect_to": "my_redirect_to_url"
}
```

2. If `type=email_change` and `MAILER_SECURE_EMAIL_CHANGE_ENABLED=true`, the old email will be used for verifying both OTPs sent to the old and new email address.

## Implementation Details
1. I refactored the common parts in `signupVerify`, `recoverVerify`, `emailChangeVerify` and `smsVerify` into a new function called `verifyUserAndToken` 
2. `verifyUserAndToken` does the following:
    * Checks if the verification is an url or otp verification
    * If it's an otp verification, check if its an sms or email otp.
3. Checks if the user is banned
4. Checks if the otp is valid

## To-Dos:
- [x] Allow url link / otp expiration to be configurable rather than restricted to 24hrs 
- [ ] Send a human-readable hash / slug instead of an otp (will be added as an enhancement in a separate PR)

### CODE REVIEW

**Review by J0 — COMMENTED** [review]
Looks fine to me. But let me sleep on it and read once more before approving

File: api/verify_test.go [hunk 1]
```diff
@@ -96,6 +96,75 @@ func (ts *VerifyTestSuite) TestVerify_PasswordRecovery() {
 	assert.True(ts.T(), u.IsConfirmed())
 }
 
+func (ts *VerifyTestSuite) TestVerify_SecureEmailChange() {
```
Comment (J0) [inline api/verify_test.go:99]: qq: is the convention of `<test_suite>_fnname` a convention within our codebase or a general Go Testing convention? Seems a little odd to mix CamelCase and snake case.

File: api/verify.go [hunk 2]
```diff
@@ -390,3 +312,81 @@ func (a *API) emailChangeVerify(ctx context.Context, conn *storage.Connection, p
...
+	}
+	return user, nil
+}
+
+// isOtpValid checks the actual otp sent against the expected otp and ensures that it's within the valid window
+func isOtpValid(actual, expected string, expiresAt time.Time) bool {
+	return time.Now().Before(expiresAt) && (actual == expected)
+}
+
+func isUrlVerification(params *VerifyParams) bool {
```
Comment (J0) [inline api/verify.go:390]: General comment:  this seems to check by excluding(e.g. if it's not an sms verification or email verification then it is a URLVerification). Would be nice if we could do something like `params.Type == URLVerification`. That said, it would require a refactor and is probably not within a scope of this PR.

**Review by J0 — APPROVED** [review]
Looks great! Thanks for the PR :)

File: api/verify.go [hunk 3]
```diff
@@ -63,7 +64,7 @@ func (a *API) Verify(w http.ResponseWriter, r *http.Request) error {
 		}
 		params.RedirectTo = a.getRedirectURLOrReferrer(r, params.RedirectTo)
 	default:
-		unprocessableEntityError("Sorry, only GET and POST methods are supported.")
+		unprocessableEntityError("Only GET and POST methods are supported.")
```
Comment (awalias) [inline api/verify.go:67]: no time for niceties 🔪

File: api/verify.go [hunk 4]
```diff
@@ -390,3 +312,81 @@ func (a *API) emailChangeVerify(ctx context.Context, conn *storage.Connection, p
...
+		}
+		return nil, internalServerError("Database error finding user").WithInternalError(err)
+	}
+
+	if user.IsBanned() {
+		return nil, unauthorizedError("Error confirming user").WithInternalError(redirectWithQueryError)
+	}
+
+	var isValid bool
+	mailerOtpExpiresAt := time.Second * time.Duration(config.Mailer.OtpExp)
```
Comment (awalias) [inline api/verify.go:360]: nice one making this configurable 👍

**Review by awalias — APPROVED** [review]
I may have overlooked it, but do we have a test case for: valid token used in combination with the email address of a different user?

File: api/verify.go (hunk 2 above)
Comment (kangmingtay) [reply api/verify.go:390]: Yeah i thought about that too but the type (signup vs recover) is tightly coupled to the `ConfirmationToken` & `RecoveryToken` fields, so it would be hard to tell whether the URL is a confirmation or recovery URL if we introduced a `params.Type == URLVerification`

File: api/verify_test.go (hunk 1 above)
Comment (kangmingtay) [reply api/verify_test.go:99]: yeah good point its not a convention, was just following the work done previously but lets standardise it to CamelCase throughout

**Comment by kangmingtay** [comment]
> I may have overlooked it, but do we have a test case for: valid token used in combination with the email address of a different user?

yeah i can add a test for that too, in this case, the verification should be rejected because the valid token doesn't belong to that user.

**Comment by asyncink** [comment]
Hi guys and thank you for your work! Can you please provide some information about your plans to support email OTP in supabase-js client?

**Comment by asyncink** [comment]
Hi guys and thank you for your work! Can you please provide some information about your plans to support email OTP in supabase-js client? @J0

**Comment by vbylen** [comment]
This is awesome @kangmingtay.

Now the OTP code sent looks like this:

`pLPxtiXsMC_D7hQqhuLQDw`

Unfortunately that's too long to copy manually. 

Especially on mobile that doesn't add much benefit over redirects.

Instead an example code should look like this:

`234 432`

That way, a user could type it manually from the email notification they receive, and not have to close the app.

I'm not sure how much of a headache it is to implement this, but it's the standard on most other services.

**Comment by kangmingtay** [comment]
hey @vbylen, with this PR (https://github.com/supabase/gotrue/pull/446), the email codes are now in the following format: `ycjho-qjvns-nadyy-kcpbu` which would be much easier for the user to either copy manually or type it manually since they are divided into even chunks.

**Comment by vbylen** [comment]
great job @kangmingtay

Now if it was possible to replace it with just 6 digits like in two-factor authentication... 😄

**Comment by bicijay** [comment]
ycjho-qjvns-nadyy-kcpbu Is not easy at all for a user to copy...

**Comment by vbylen** [comment]
@bicijay agreed, this was a missed opportunity

@kiwicopple thoughts?

**Comment by kangmingtay** [comment]
@bicijay @vbylen we're working on a PR to shorten the email otp to [6-10] digits long, thanks for the feedback everyone!

**Comment by kaaloo** [comment]
Is there any ongoing work on this @kangmingtay ?

> @bicijay @vbylen we're working on a PR to shorten the email otp to [6-10] digits long, thanks for the feedback everyone!

**Comment by J0** [comment]
Hey  @kaaloo,

The work by @kangmingtay to shorten the email otp to 6-10 digits has been merged. Do check out the`/generate_link` endpoint on the [README](https://github.com/supabase/gotrue) and let us know if you have any questions.

Thanks!
