### PR TITLE
Change Discord's discriminator type to string

### LINKED ISSUE #442: Discord discriminator base length isn't respected if it's #0999 or less.
# Bug report

## Describe the bug

If you have a Discord discriminator that is `#0999` or lower, the metadata stored doesn't respect the 4 int/string length and will show up as `#999`. In my case it just shows up as `#1`.

## To Reproduce

1. Have a Discord account that has a discriminator no higher than `#0999`
2. Sign in using Discord as the provider
3. Check the user metadata, it should only show `{username}#999` or the respective discriminator.

## Expected behavior

Discriminator base length should be respected and show `{username}#0999` so that it contains the correct information for the user.

## Screenshots

I changed my discriminator for this one to be in line with what's written above.
Screenshot 2022-04-08 at 00 35 04

## System information

- OS: macOS
- Version of supabase-js: 1.33.3
- Version of Node.js: v16.14.2

## Additional
Looking at the `discord.go` file, I believe the Discriminator should be a string and not int, as that's what Discord is providing via the API.
But I'm not familiar with Go, so not sure what the *standards* are.

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

## What kind of change does this PR introduce?

Fix #442

## What is the current behavior?

(Referenced from the issue)
> If you have a Discord discriminator that is #0999 or lower, the metadata stored doesn't respect the 4 int/string length and will show up as #999. In my case it just shows up as #1.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by Xanewok — APPROVED** [review]

File: api/provider/discord.go [hunk 1]
```diff
@@ -76,11 +77,15 @@ func (g discordProvider) GetUserData(ctx context.Context, tok *oauth2.Token) (*U
 
 	var avatarURL string
 	extension := "png"
-	// https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints:
-	// In the case of the Default User Avatar endpoint, the value for
-	// user_discriminator in the path should be the user's discriminator modulo 5
 	if u.Avatar == "" {
-		avatarURL = fmt.Sprintf("https://cdn.discordapp.com/embed/avatars/%d.%s", u.Discriminator%5, extension)
+		if intDiscriminator, err := strconv.Atoi(u.Discriminator); err != nil {
```
Comment (kangmingtay) [inline api/provider/discord.go:81]: will the discriminator returned from discord be "#0999" or "0999" here? if it's the former, you'll need to strip out the "#" before passing it into `strconv.Atoi` or it will always return an error

**Review by kangmingtay — CHANGES_REQUESTED** [review]

File: api/provider/discord.go (hunk 1 above)
Comment (kangmingtay) [reply api/provider/discord.go:81]: maybe @PhaxeNor would know? :)

Comment (PhaxeNor) [reply api/provider/discord.go:81]: Discord only returns numbers (as string ofc), so "0999" in this case.

**Review by kangmingtay — APPROVED** [review]

**Comment by GaryAustin1** [comment]
@kangmingtay
I'm not sure this has anything to do with it, but lots of users are reporting Discord sign in issues only on Supabase projects this morning.
