### PR TITLE
fix: improve perf in account linking

### LINKED ISSUE #1390: Account linking queries do a sequential scan on the users/identities table by default in managed Supabase
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm currently working on a project with >1 million users in managed Supabase and we were recently seeing heavy database load as a large number of new users were signing up. Looking at the query performance report data, we found two queries taking up 80% of our compute:

- `SELECT identities.created_at, identities.email, identities.id, identities.identity_data, identities.last_sign_in_at, identities.provider, identities.provider_id, identities.updated_at, identities.user_id FROM identities AS identities WHERE email ilike any ($1)`
- `SELECT users.aud, users.banned_until, users.confirmation_sent_at, users.confirmation_token, users.confirmed_at, users.created_at, users.deleted_at, users.email, users.email_change, users.email_change_confirm_status, users.email_change_sent_at, users.email_change_token_current, users.email_change_token_new, users.email_confirmed_at, users.encrypted_password, users.id, users.instance_id, users.invited_at, users.is_sso_user, users.last_sign_in_at, users.phone, users.phone_change, users.phone_change_sent_at, users.phone_change_token, users.phone_confirmed_at, users.raw_app_meta_data, users.raw_user_meta_data, users.reauthentication_sent_at, users.reauthentication_token, users.recovery_sent_at, users.recovery_token, users.role, users.updated_at FROM users AS users WHERE email ilike any ($1) and is_sso_user is false`

Running those queries manually indicated that the referenced tables were being sequentially scanned by these queries and the indexes were not being used. I believe I was able to trace the calls done to the account linking code, see:

https://github.com/supabase/gotrue/blob/5ad703bddc6ec74f076cbe6ce1f942663343d47a/internal/models/linking.go#L109-L122

So, I'm creating this bug report here, but if I'm wrong about this, please move this to where it does belong.

## To Reproduce

1. Have a lot of users
2. Create a new user using OAuth
3. Watch the requests take a while to complete

## Expected behavior

Account creation should be quick even when there are many users.

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Currently, we use an `ilike` which doesn't use the index on `auth.identities.email`. Since the emails in the `verifiedEmails` slice only contains lowercased emails, and the `auth.identities.email` are also guaranteed to be lowercase, there is no need for a case-insensitive search
* The partial unique index (`users_email_partial_key`) in auth.users is defined on the condition that `is_sso_user = false`. However, the query uses `is_sso_user is false` which causes it to not use the index ever (along with `ilike`). It would be much faster to do `lower(email) = any (?)` rather than `email ilike any (?)`
* Fixes #1390

### CODE REVIEW

File: internal/models/linking.go [hunk 1]
```diff
@@ -109,14 +109,14 @@ func DetermineAccountLinking(tx *storage.Connection, config *conf.GlobalConfigur
...
-	if terr := tx.Q().Eager().Where("email ilike any (?)", verifiedEmails).All(&similarIdentities); terr != nil {
+	if terr := tx.Q().Eager().Where("email = any (?)", verifiedEmails).All(&similarIdentities); terr != nil {
 		return AccountLinkingResult{}, terr
 	}
 
 	if !strings.HasPrefix(providerName, "sso:") {
 		// there can be multiple user accounts with the same email when is_sso_user is true
 		// so we just do not consider those similar user accounts
-		if terr := tx.Q().Eager().Where("email ilike any (?) and is_sso_user is false", verifiedEmails).All(&similarUsers); terr != nil {
+		if terr := tx.Q().Eager().Where("lower(email) = any (?) and is_sso_user = false", verifiedEmails).All(&similarUsers); terr != nil {
```
Comment (tasgon) [inline internal/models/linking.go:119]: This query still takes a while when I test it on our project. I looked through the indexes and we have one on `email`, but not `lower(email)`. Adding one seemed to resolve the problem, but you may have better ideas here.

**Review by J0 — DISMISSED** [review]

File: internal/models/linking.go (hunk 1 above)
Comment (hf) [reply internal/models/linking.go:119]: Yeah agreed this is not going to fix the performance issues. To have queries be fast you can't use `ilike` or functions like `lower` on the column.

We need to add a (non-unique) index with `text_pattern_ops` as well @kangmingtay

Comment (kangmingtay) [reply internal/models/linking.go:119]: @hf @J0 will need to measure the impact of adding / updating the index on larger tables

this change improves the performance slightly without sacrificing any downtime

Comment (J0) [reply internal/models/linking.go:119]: Maybe we can start with this and then iterate?

**Review by J0 — APPROVED** [review]
