### PR TITLE
fix: empty password update should return explicit error

### LINKED ISSUE #294: Admin password length for password resets
You can reset passwords to a password of length zero. The guardrails which apply to the password creation do not seem to apply to resetting the password.

Specifically just the guardrail that prevents zero length passwords. A password length of 1 character is not allowed.

Passwords of length zero should not be possible

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* `PUT /admin/users/<user_id>` with a password of length 0 should return an explicit error 
* `PUT /user` with a password of length 0 should return an explicit error 
* Standardise invalid password update error response for both `PUT /user` & `PUT /admin/users/<user_id>` to return a 422 unprocessable entity
* Resolves #294

### CODE REVIEW

**Review by awalias — APPROVED** [review]

File: api/admin.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ type adminUserParams struct {
 	Role         string                 `json:"role"`
 	Email        string                 `json:"email"`
 	Phone        string                 `json:"phone"`
-	Password     string                 `json:"password"`
+	Password     *string                `json:"password"`
```
Comment (kangmingtay) [inline api/admin.go:20]: Using a pointer here because when the following request bodies are decoded, the password field in the struct will default to an empty string. This means that we won't be able to tell if the original request intended to modify the password or not. 

```
{ "email": "xxx", "password": "" } 
or 
{ "email": "xxx" }
```

Using a pointer ensures that if the password field is missing, decoding the request body will assign a nil pointer to `password`.
